

MQTT_ERR_AGAIN=-1
MQTT_ERR_SUCCESS=0
MQTT_ERR_NOMEM=1
MQTT_ERR_PROTOCOL=2
MQTT_ERR_INVAL=3
MQTT_ERR_NO_CONN=4
MQTT_ERR_CONN_REFUSED=5
MQTT_ERR_NOT_FOUND=6
MQTT_ERR_CONN_LOST=7
MQTT_ERR_TLS=8
MQTT_ERR_PAYLOAD_SIZE=9
MQTT_ERR_NOT_SUPPORTED=10
MQTT_ERR_AUTH=11
MQTT_ERR_ACL_DENIED=12
MQTT_ERR_UNKNOWN=13
MQTT_ERR_ERRNO=14
MQTT_ERR_QUEUE_SIZE=15


errStr={}
errStr[MQTT_ERR_AGAIN]="MQTT_ERR_AGAIN"
errStr[MQTT_ERR_SUCCESS]="MQTT_ERR_SUCCESS"
errStr[MQTT_ERR_NOMEM]="MQTT_ERR_NOMEM"
errStr[MQTT_ERR_PROTOCOL]="MQTT_ERR_PROTOCOL"
errStr[MQTT_ERR_INVAL]="MQTT_ERR_INVAL"
errStr[MQTT_ERR_NO_CONN]="MQTT_ERR_NO_CONN"
errStr[MQTT_ERR_CONN_REFUSED]="MQTT_ERR_CONN_REFUSED"
errStr[MQTT_ERR_NOT_FOUND]="MQTT_ERR_NOT_FOUND"
errStr[MQTT_ERR_CONN_LOST]="MQTT_ERR_CONN_LOST"
errStr[MQTT_ERR_TLS]="MQTT_ERR_TLS"
errStr[MQTT_ERR_PAYLOAD_SIZE]="MQTT_ERR_PAYLOAD_SIZE"
errStr[MQTT_ERR_NOT_SUPPORTED]="MQTT_ERR_NOT_SUPPORTED"
errStr[MQTT_ERR_AUTH]="MQTT_ERR_AUTH"
errStr[MQTT_ERR_ACL_DENIED]="MQTT_ERR_ACL_DENIED"
errStr[MQTT_ERR_UNKNOWN]="MQTT_ERR_UNKNOWN"
errStr[MQTT_ERR_ERRNO]="MQTT_ERR_ERRNO"
errStr[MQTT_ERR_QUEUE_SIZE]="MQTT_ERR_QUEUE_SIZE"

# return the error string associated with an error number

def get_MQTT_Error_String(errNo):
    if errNo<MQTT_ERR_AGAIN or errNo>MQTT_ERR_QUEUE_SIZE:
        return errStr[MQTT_ERR_ERRNO]

    return errStr[errNo]

